### ISSUE TITLE
STREAM :: 仕事の色々

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#12]
数え上げ問題：3年の一部に食い違いあり。

**Comment by b0101** [comment]
原因判明。「教」だ。

**Comment by b0101** [comment]
[moodle 2.9](https://moodle.org/mod/forum/discuss.php?d=313329#p1254582) installed.

**Comment by b0101** [comment]
採点は来週でいいか :+1:

**Comment by b0101** [comment]
月曜の準備終了。これは助かる。こうでなければ。

**Comment by b0101** [comment]
機械学習のレクチャー記事読み始め

**Comment by 630E6617** [comment]
So, I will finish survey on JSAI journals over 5 years today! :angry:

**Comment by 630E6617** [comment]
仕事系の大部分はあっちに書けばいいか。こっちはプログラミング系のいろいろ。

**Comment by 630E6617** [comment]
一つ大事な設問を作ってなかったことに気づいた。ふむ、ここを潰せば後は頑張ってもらうだけ。
