### ISSUE TITLE
NHK生命大躍進

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#16]
目ができたのは、植物の持つDNAが動物に取り込まれて、葉緑素に関するDNAが取り込まれたからだそうだ。  
そして、目の機能が大きく進化したのは、遺伝子が半数にならないもの同士の受精が2回起きたため、遺伝子総数がそれまでの4倍になって、冗長性が複雑さを産み出す源になっただそうだ。

なんというなんでもありな説明。そしてどちらもやはりカンブリア紀。

DNAは設計図とかプログラムというよりも、オートマトン・プールと言った方がシックリ来る。お互いがお互いに影響を及ぼし合っているのだから、次元はよくわからないけど、セルラーオートマトンとも言えるかも。

**Comment by b0101** [comment]
オートマトンプールならそこに情報処理能力を見出してもいいんじゃね。

**Comment by b0101** [comment]
http://www.nhk.or.jp/seimei/special.html

* 第2回6/7
* 第3回7/5

**Comment by 630E6617** [comment]
第2回

* 卵を雑菌から守るための殺菌物質が変化したものが栄養豊富な母乳の期限

**Comment by 630E6617** [comment]
第3回：知性の発生

ながら観をしたせいか、あまり面白くなかった。脳の発達？に関係するFOXP2遺伝子に変化があるのはわかったけど、その影響が現在進行形の研究であまり言えることがなかったせいだろう。脳が現在の人類よりも大きなネアンデルタール人がどうしてより高度な知性を持たなかったのか説明あったか？ 

3回見終わって感じたのは、遺伝子システムは色々と都合の良い偶然が積み重なればいくらでも進化できるよくできたシステムだなあということでした。
