### ISSUE TITLE
関数的プログラミング言語入門の到達目標

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#17]
* 再帰関数の使いこなしが到達目標だと思っていた
* 止めたほうがいいらしい
* では*高階関数によるプログラムの構成法*はどうだろうか
    * 関数型言語っぽい
    * アルゴリズムを考える問題からプログラムを書く問題に若干シフトできる
    * プログラム作成法としては新規なものはない
    * 再帰関数に注目すると実装主体であり、高階関数に注目すると仕様主体とみなせる。役に立つのは後者では
* 型の話はどこに行った。すべきか？

![](https://lh3.googleusercontent.com/42bD1ZdDom72-GnPEK3-6h1ggtbgcxUp7GlS_dbPGALd=s960-no)

**Comment by b0101** [comment]
いろいろシミュレーションしてみて一つの問題が浮かび上がった。

この内容だと座学で十分じゃね？

書けるようになる必要は最初からなかったんだ。

**Comment by b0101** [comment]
ちょっと真面目に考えたほうがよい。

リストの諸々を省略すると以下を導入することができるかもしれない。

 * `[] a`という**パラメータ付の型**
 * `Ord`などの**型クラス**

パラメータ付の型はSTLの導入として有用。型クラスはOOPLの導入として有用。

パラメータ付の型はあまり説明することはない。単に暗記項目が増えるだけ。STLという例を出せるかもしれないだけ。

一方で型クラスはリストの話を2回削らないと入らない。そしてこの話と高階関数の両方やるのは大変。。。

だが、これまで強調してきた高階関数とは引数の型を拡張するものであり、型にまつわるトピックということではこれらには非常に共通点がある。実際、

* パラメータを取る型
* 型をまとめるクラス
* 関数型

は全て旧来のプログラミング言語における型を拡張する流れとして位置づけることができる（ここまであまり関数型言語とは無関係）。これを支えるのが（例えばHindley-Milner型の）型推論・型検査。

再帰は必要か？ ライブラリ実装の話になってしまうならやめてもいいかも。中身を説明せずに`fold`, `filter`, `map`を導入してもいいかも。

ふむ。関数型やめて型の話にするか。。。

**Comment by b0101** [comment]
問題点→ 適当な教科書が今以上にない！

**Comment by b0101** [comment]
### 今年の方針

今更、方針の大修正は出来ないので、気持ちこちらに振るとして再計画。

 # | 内容
--- | ---------------------------------
07 | 型のテストの予習＋リストの導入
08 | 型のテスト + リストを処理する関数とその型
09 | リストを再帰で処理する（なぜなら帰納法に似ているため証明しやすい）
10 | 再帰の穴埋め問題＋再帰関数の組合せ
11 | 再帰関数から便利な高階ライブラリ関数へ
12 | 高階関数の型
13 | 型クラスの導入
14 | クラス、高階関数、引数付きの型という型の拡張
15 | 言語の進化について

**Comment by b0101** [comment]
この内容への変更、前もって配布資料なんか作らないほうがいいかもしれない。即興でmarkdownでキャッチフレーズを列挙しながら進めたほうがいいかも。
プログラムだけは用意しておくべきか。そうしようかな。

**Comment by b0101** [comment]
この表は大改造のように見えて、まだ大改造ではない。
本来ならこの内容に加えて**部分適用**まで入れなければ。
そして、できるなら

* lambda式
* section

まで入れられるといいのだが、それは欲張り過ぎというもの。

* mixfix

があると関数と演算子の違いがわかってsectionも入れてもいいかという気になるけど、無理すぎ。

**Comment by b0101** [comment]
プログラムを書かせるのが目的でなければ、意外にサクサク進むかもしれない。8回目の内容に9回目の内容（型変数）が移動してくるかも。

**Comment by b0101** [comment]
多分、これは1割しかついてこれない。

```haskell
addTrue :: [Bool] -> [Bool]
addTrue l = True : l

addFalse :: [Bool] -> [Bool]
addFalse l = False : l
 
permutations :: Int -> [[Bool]]
permutations 0 = [[]]
permutations n = map addFalse (permutations (n - 1)) ++ map addTrue (permutations (n - 1))
```

**Comment by b0101** [comment]
多分、「プログラミングするときに自分で型を定義することがある」というのもあまりついてこれない。

**Comment by b0101** [comment]
大体設計が終わり、もうこの方針で公示してしまったので、ここから先はon-the-flyで現場の作業。
この項終わり。

**Comment by b0101** [comment]
Curry-Howard同型対応も言葉だけだすか？ 依存型も。そもそも Hindley-Milner type inferenceを志向する以上、それは時間の問題のような。

**Comment by b0101** [comment]
Amazonで探したけど教科書は本当にない。教える価値ないということだろうか?  プログラミング言語の基礎理論が一番近いかもしれない。読んでないけど。うーむ。

**Comment by b0101** [comment]
Javaに型変数あるじゃん。じゃ、教授にガタガタ言われる事はなかろう。見切り発車していいか。

**Comment by b0101** [comment]
Number 08 finished without any problem.

**Comment by b0101** [comment]
### introduction of partial evaluation

流れを考えると多相型→`data`-`class`→高階関数の順がよさそうだ。

 # | 作業 | 内容
--- | ------|-------------------------
07 | 型のテストの予行 |リストの導入（空リストからの再帰的な定義、`:`による追加、要素とリストの型の関係）、関数はまだ導入しない、パターンマッチング
 | | 空リスト、`:`、追加する関数、パターンマッチング、`first`, `second`
08 | **型のテスト** | 型変数の導入による関数の型定義（型変数になる場合とそうでない場合の区別、リストを処理する1引数再帰関数、その関数の型、`for`文がないこと
 | | `length1`, `sum1`, `and1`, `or`, `product`, `sumPlus`, `from1toN`
09 | |多相型、多相型関数、多引数多相型関数における型に関する連立方程式, 高階関数の導入
 | | `length1`, 注`minimum1`は型制約がないので書けない, `reverese1`, filter
10 | **リストおよび多相型のテスト、再帰関数の穴埋めも含む**   | 型定義、クラスに基づくデータ型の定義（`map`, `filter`, `zipWith`, `fold`)
 | | `fs`, `snd`, `length`
11 | | 型クラスの紹介、メソッドの意義
 || `Eq`, `Ord`, `data`, `Show`
12 |  |  型クラスに関する演習、いくつかのライブラリ関数の再定義
 || `elem`, `maximum`
13 | **型クラス、メソッド関数のテスト** | | ライブラリ高階関数の紹介、多相性を持つ高階関数（`map`, `filter`, `zipWith`, `fold`)の応用
 || `member`, `minimum1`, `maximum1`, `sort`
14 | | 高階関数の型
 || 演習よりは他の様々なオブジェクト指向言語の説明にした方がいいかも
15 | **高階関数に関するテスト** | 部分適用、言語の進化について
 || 説明のみ

**Comment by b0101** [comment]
1. 型からクラスというプログラミング言語が取り扱うデータの進化の流れ、それによるメソッドという概念の習熟。
1. オブジェクト指向以外の近年注目を浴びている関数型言語の特徴の一つである高階関数によるプログラムの再利用、そのために頻繁に用いられ、自由な関数利用を可能にする部分適用という概念を理解する。

![](https://lh3.googleusercontent.com/OOBpCn6QsuGgKaUmdtIuJAVx5724vulynDwUE5R9oYPs=w1265-h939-no)

**Comment by 630E6617** [comment]
関数の進化の1面は引数返値の型の持つ自由度から見ることができる。

* 一つの型のみ許す
* 型引数を許す
* 型のグループを許す（これはparametric/ad-hoc polymorphismの両方に対応）
* 関数を許す
* 段階的な適用を許す（これだけ異質）
* 型間の関係記述を許す


異質なものを羅列するなら

* keyword引数
* オプショナル引数
* 部分適用

いずれにせよこれでかなりの部分が説明できる。

### ad-hoc polimorphism and parametric polmorphIsm
http://itpro.nikkeibp.co.jp/article/COLUMN/20060905/247156
まず，repeated関数や++演算子のように，関数の型情報の一部をパラメータ化した中立的な定義をすることで，関数そのものの振る舞いを変えることなく得られる多相性です。これをパラメータ多相（parametric polymorphism，パラメトリック多相）と呼びます。一方で，Numクラスで定義されている+演算子などのように，型によって変わる振る舞いを型クラスなどを通して関数に付け足すことで発生する多相性があります。これを「アドホック多相（ad-hoc polymorphism）」と呼びます。

**Comment by 630E6617** [comment]
型変数なしのレベルでチェックすると半数が脱落した。まあそういう現実。

**Comment by 630E6617** [comment]
部分適用はJavascriptにもJavaにもあるねえ。結構応用広いな。

**Comment by 630E6617** [comment]
部分適用はpythonにもrubyにもあるねえ。でも**初心者向けのチュートリアルの最初の100ページに出て来ないなら言語の幹ではない**だろう。なので会社なら使ってはいけないレベル、部分適用の重要性の根拠に入れない方がいいレベルと判断しましょう。

**Comment by 630E6617** [comment]
資料作っていて気づいたけど、

* `deriving`はparametric polymorphismの
* `instance`はad-hock polymorphismの

ためのメカニズムなんだろうか。

**Comment by 630E6617** [comment]
### no.11 summary

* OOPLの現状
   * 2015年期待される言語、OOPLの割合、作成年の傾向
* 特定の型のみを受付ける多相の多様
* ただし、parametric多相だけではないこと→ふるまいの特殊化：多対1 vs 多対多
* `instance` の導入
    * `Ord`の修正：**意味ある変更**
    * `Show`の修正： 同上
* 結論：**ad-hoc多相**
* 補足（この回にすべきかどうかは疑問）
    * Javaにおいては`interface`と呼ばれるものであること。
    * パターンマッチングは型ではなく値による分岐であること。

**Comment by 630E6617** [comment]
なんでこんなことをgithubに書くのかというと、しばらく色々やってみて、むしろ誰も見ないであろうここの方が想定する対象として適切だからなのでした。。。

**Comment by 630E6617** [comment]
型の話ということで言えばこれもそうか。

![](https://lh3.googleusercontent.com/zxnhKLqPiEqQTN1ibCH2KX5k_mDceJ3ZsLzC2BL78NRd=w1229-h950-no)

**Comment by 630E6617** [comment]
11回目特に問題なし。

**Comment by 630E6617** [comment]
計画練り直し。つめ込まなくていいだろう。

\# | contents
--- | --------
12 | 高階関数の導入 
13 | 高階関数の型の自習
14 | 部分適用 
15 | closing notes

**Comment by 630E6617** [comment]
依存型は言葉は知っているけど、利点を説明できない。:-1:

**Comment by 630E6617** [comment]
死ぬほど自習問題を作らないと高階関数は全然身につかないな。
まあ、それは来年の課題ということにして、次の話題（最後の話題）に進もう。
次の話題は型を問う問題にはならない。かと言ってプログラミングの問題にもしにくい。
コンパイルエラーになるかどうか、何が返ってくるかの問題か。。。最終回までにオンラインテストの準備をしないといけないか。。。。
そこさえ超えれば開放される :+1:

**Comment by 630E6617** [comment]
14回目終了。かなりいろいろ詰め込める。これでほぼ終了。
クロージングのための資料集め（本来は1回目に見せるべき）があるので作業は大変だけど、もうこれ以上知識の詰め込みをしなくていいのはよいことだ。あとは作文させようか。

**Comment by 630E6617** [comment]
15回目の内容は勉強しろよで終わるつもりだったけど、google chartsを利用しようとしていて自分で高階関数や部分適用を使うはめになった。これはすごくいい例題になっている！ ということで急遽webページの作成における高階関数、部分適用の利用という実践編をすることにした。これで意義が少しは伝わるのではないだろうか。。。

**Comment by 630E6617** [comment]
最後の最後になってイベントハンドラが高階関数であることを言っておけばよかったと反省。実はいろいろなものが連携していたのだった。

**Comment by 630E6617** [comment]
終了。全然伝わった感じがしないのは毎年のこと。。。まあ、意義付けといことでは今年の枠組みが一番いいな。来年以降もこの位置づけでしよう。ということでこのissue終了。
