### ISSUE TITLE
STREAM :: 読書

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#21]
6月24日にグレッグ・イーガンの訳本新刊[ゼンデギ](http://www.hayakawa-online.co.jp/shopdetail/000000012717/date_2015_06/page1/order/)

**Comment by b0101** [comment]
5月22日にスティーブン・バクスター、タイム・シップ
http://www.hayakawa-online.co.jp/shopdetail/000000012690/

**Comment by b0101** [comment]
Kindle本、ポイント還元サービス中に付きグレッグ・イーガンまとめ買い。

**Comment by b0101** [comment]
大西英文法本も購入。早速読書開始。

**Comment by b0101** [comment]
グイン・サーガ136もkindle化

**Comment by b0101** [comment]
グレッグイーガン全部買ったぞ！

**Comment by b0101** [comment]
グインサーガ136、イリスの炎。グイン一代記かと思っていたけど、どんどん次世代の重みが増している。これがいつぞやのドラゴンクエストみたいに子らが「親を助け」ということでグインの話が収束するのならいいのだけど、そうでもなければ、作者が死んでも続くグインサーガは、読者＝僕が死んでも続くことになりそうで怖いわ。

**Comment by b0101** [comment]
大西泰斗、英文法を壊す、読了。

彼は文法ではなくイメージから英語を理解せよというのだけど、最近の膨大な英文からベイス確率として機械学習で得られる文法観に非常に近いところにいるようだ。説得力を感じる。

一方で、間接話法で従文の時制が主文に引きずられるかどうか、あることを主張するのに完了形を使うのか過去形を使うのかは、コンテキストにせいぜいうっすらとしか現れてこない（従っておそらくはとても長い距離があるだろう）話者と対象の間の関係や感情と言ったものからしか、解釈・接地できないのではないかと思う。そういったもの（レイヤーが違うところを流れる情報）をも含めた隠れマルコフモデル化になっているのかしらん、今の機械翻訳。

**Comment by b0101** [comment]
amazonのポイント還元祭りで大量に買ったけどそのうち読んだことがないのは、*イリスの炎* と *英文法を壊す* くらい。春の読書祭りも終わったな。

**Comment by b0101** [comment]
間違えてテッドチャン、あなたの人生の物語、買ってしまっていた。買う価値ないだろ。。。
そろそろ弱虫ペダル40だ。

**Comment by 630E6617** [comment]
そうか、ジーリーが出てくる壮大な宇宙史を書いたのはバクスターか。じゃあタイムマシン買わないといけないなあ。。。

**Comment by 630E6617** [comment]
むかーし買っていたこの本突然読みたくなった。と言っても人工知能サーベイがまだ2週間分くらい、SF本が数冊、*Song of Ice & Fire*が待っているので、かなり強引な割込みをしなくちゃいけないなあ。

![](https://lh3.googleusercontent.com/cWhruabqLOUhMBZYqgS4IasIUra0Qm-RdMwk8s1bDjri=w936-h1260-no)

**Comment by 630E6617** [comment]
#58 読了

**Comment by 630E6617** [comment]
人工知能、vol.29, no.5の特集の一つが「SFとAI」なんだけど、21世紀のハードSFがあまり出てこない。一方、同じ号の別の特集に京都大学iPS細胞研究所の方が生命や個性、知性と物質の境界に関する記事を書いている。この中で触れられているのが「ディアスポラ」、「ぼくがぼくであること」、「エキストラ」、そして「適切な愛」。かなり読み込まれているようだ。特集「SFとAI」には1回しか出てこないグレッグ・イーガンがこの一篇にオンパレードがこの一篇でオンパレードとは何たることぞ :exclamation: :boom:

**Comment by 630E6617** [comment]
人工知能の学会誌の網羅もあと１冊！

**Comment by 630E6617** [comment]
人工知能読み終わり。そして、今日はNASAテクニカルライティング1章読み終わり。

**Comment by 630E6617** [comment]
ゼンデギまで1週間。という事を考えて読むものを選ばねば。

**Comment by 630E6617** [comment]
ゼンデギ在庫確認。さて、どうしようか。

**Comment by 630E6617** [comment]
やっぱりゼンデギ購入 :grin:

**Comment by 630E6617** [comment]
グレッグ・イーガン、ゼンデギ、早川書房、2015
読了。
時間がないのでとりあえずメモ。

* 2009年に書かれてはいるけどここ近年の（汎用）人工知能の流れがわかっていたような描写
* 知性があるかどうかのチューリングテストのように、これは自分かどうかを判断するidentity testがあってもいいかも
* mind uploadingにおいて自分の意識は移植できないのだろうか？ というか寝ることは死ぬのと一緒だという事実と折り合いを付けなければ。
* 不完全な自意識を作ることは罪なのだろうか

**Comment by 630E6617** [comment]
ゼンデギがkindle化されていた。一ヶ月足らずでkindle化されるとは全くの誤算。それくらいなら待てたのに :cry:

**Comment by 630E6617** [comment]
フカシギのお姉さんの本購入ｗ

**Comment by 630E6617** [comment]
2015年9月はなぜか圏論出版祭り

* 圏論の歩き方
* 圏論原著第2版

でも、多分どちらも到達点は *Introduction to Concrete Mathematics*よりも高いと思うわ。
基礎の基礎だけで本にしてしまうようなことはなかなか研究者として選択しないだろうなあ。
