### ISSUE TITLE
教えるということと評価することに関する独り言

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#25]
絶対評価じゃないと「どうして同じように解いたのに点数が違うのか」という *クレーム* が出るのが怖いものだけど、もうちょっと積極的に導入してもいいかもしれないと思うようになってきた。
評点の設定でそういうイメージは随分と払拭できるかもしれない。

* 早く解けるかどうかを合否にマッピングするのは大きな間違い
* 効率的に問題を解けるかどうかで理解度・習熟度を図るのは妥当

従って相対評価はAAの判定になら使っても格段文句は出ないはず。

**Comment by b0101** [comment]
やはり相対評価はすべきだな。合格レベルと要求レベルは違うとしか言いようがない。なら、2重化すべきだ。

**Comment by b0101** [comment]
これだけSNSが普及しているなら、それを使わせない手はないだろう。
と言いたいところだが、直接会って話すことに意義を見出す人が多い。
でもそれは講義の場ではないのか？

**Comment by b0101** [comment]
話すことが早く終わったら、考える時間を与えればいい。というより考える時間にするべき。
