### ISSUE TITLE
Mendeley on Android

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#36]
[6月に公開](http://blog.mendeley.com/mobile-2/mendeley-for-android-launching-in-june/)。楽しみ。

**Comment by b0101** [comment]
So June has come!

**Comment by 630E6617** [comment]
来た！ 長かったなあ。

**Comment by 630E6617** [comment]
寝転がって論文を読める。しかし、大きなタブレットが欲しくなった。

**Comment by 630E6617** [comment]
ノートが編集できないのか？！
