### ISSUE TITLE
github, slackをどう使うべきか

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#4]
### milestoneとtagとissueの位置づけについて再考
日記ファイルを完成させるのをこのリポジトリの目的にしたらどうだろう。
1日1行のファイルを更新するためにその日にした作業をissueに対応させて、適当な期間をマイルストーンに設定。その期間が終わったらissueを閉じる（あるマイルストーンに含まれるissueを全部閉じる機能はあるだろうか？）。labelは作業内容。

ブランチは複数の数日掛かる仕事が続く場合に作成。仕事が終わるとTRUNKにmerge。ああ、そうすると1日の中を箇条書きにするのはやめて
```
yyyy-mm-dd: task1
yyyy-mm-d1: (to d2) long task2
```
のような行で書いていくのがよさそうだ。

対応をまとめると：

* ~~diary ファイル: 日記（最終目的物）~~
* **Today I Finished** (終了タスク記録ファイル）: 最終目的物
* commit：一つのタスク（またはその1日分）が終わった。issueがあればそれへのリンクを持つ。
* ~~branch: 数日にまたがるタスク~~
* issue: タスク中のつぶやき
* tag: タスクの分類
* milestone: 1年か期かクォーターに対応するまとまり。

**Comment by b0101** [comment]
ということで今日commitするなら
```
2015-05-05: 日記の方針を決めて作成開始 #4
```
ということになるはず。

**Comment by b0101** [comment]
この流儀でbranch作ると機械的なmergeは失敗することが判明。gitの全機能を使おうとするのはやめたほうがよさそうだ。

また、diaryファイルに書く内容とcommitメッセージがかなり似通ったものになる。diaryファイルを第1に考えたいところだけど、issueへの自動リンクができるのはcommit messageだけ。そしてissueにコメントをつけることはcommitすることになるので、commitメッセージの方が粒度は細かくなる。そうするとdiaryファイルはもう少し粒度の荒いところを目指すべきだろう。一つのタスクが終わった時だけ書き込むようにしようか。（だとするとbranch mergeもうまく行くだろう。もっとも使わないことにしたけど。）

**Comment by b0101** [comment]
`git blame`を使えばファイルからcommit message、commit messageからissueへ遡ることは簡単だ。では、やはり閉じたissueへのリンクとして終了タスクファイル(done-yyyy.md)を作るのが正解のようだ。

**Comment by b0101** [comment]
### どこに何を書く？

site | object
---- | ------
self hosted blog by ghost | ここは話題限定、それなりのボリュームのもののみ置きたい。実際には研究内容のみ。一番近いのはmedium。
github.com | ツイートレベルの雑談色々
slack.com | closedなのだからここが研究拠点？ 生データを置くにはいいけど、書きながら考えをまとめるにはエディタが気持よくない。ぼかした形でblogに書きたくなる。。。ツイートレベルの研究ネタなら被らないか。一方で研究ネタのツイート場所としては不満はない。ghostがチャネルを実装し、チャネル単位でパスワードを掛けることができるようになれば、そして任意ファイルのアップロードができるようになれば、この有料サービスは切ってもよい。あるいはツイートまとめて一つのエントリーにしてもいい

ふむ、ここは雑談。ガンガンissue立ててつぶやくけど、研究ネタは人には見せない。
研究ネタはslackに書いて、ある程度まとまったらblogでネットデビュー。そして本当に大事なものはslackから原稿に持っていけばいいか。

ではガンガンissue立てよう :+1:

一方、slackとghostは将来的には目的が被りそうだ。ghostにchannelが実装されたら考えてみなくては。

**Comment by b0101** [comment]
ということで`research`ラベルは削除。

**Comment by b0101** [comment]
将来的に（個人用）slackを捨てるのなら、研究室用slackを有料プランに切り替えるのがいいかも。
人数が５人を超える時だけ無料。そうでなければ有料。自分以外に４人。。。超微妙。

**Comment by b0101** [comment]
一ヶ月ほどやってみて、githubを公開の場、blogをパスワード付、そして毎年溜まっていく資料置き場さえ確保すれば、slackは要らないという結論。やはり個人用Slackをなくすのがよさそうだ。

**Comment by b0101** [comment]
[exporter](https://gist.github.com/b0101/05a2632b8b9c3b082be2) 作成。

**Comment by 630E6617** [comment]
数日前にまず個人用Slackをfree planに変更した。

place | purpose
-------- | ----------
github | daily tweet
ghost | reseach note (Yes! It's a **research note**!) 
private rep. | research data 
rep. on github | I have nothing to be public
gitter | complete garbages
slack | repository for jobs/tasks
