### ISSUE TITLE
STREAM :: OSS watch

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#45]
各種ソフトウェア更新情報とエールなど

**Comment by b0101** [comment]
かなり期待できそう。llvm 3.6も使えるのかもしれないし

**Comment by b0101** [comment]
# [ghost](http://dev.ghost.org/public-dev-meeting-june-2nd/)
the next ghost はまだまだ先のようだ。でもメジャーバージョンアップに相当するかも。

**Comment by 630E6617** [comment]
owncloud client 1.8.2 リリース :+1:。multi account対応はされたのだろうか？ バージョンの増え方からして無理かなあ。

**Comment by 630E6617** [comment]
あ、今週はghc update予定の週。

**Comment by 630E6617** [comment]
## Ghost should not use a URL that is a translation of its title as a Chinese sentence!

**Comment by 630E6617** [comment]
[GNU screen 4.3.0](http://lists.gnu.org/archive/html/screen-users/2015-06/msg00004.html) wow!

**Comment by 630E6617** [comment]
[ghc 7.10.2 rc1](https://downloads.haskell.org/~ghc/7.10.2-rc1/docs/html/users_guide/release-7-10-2.html)

**Comment by 630E6617** [comment]
ghc HEAD has [only 7 issues](https://ghc.haskell.org/trac/ghc/query?status=infoneeded&status=patch&status=merge&status=upstream&status=new&group=status&milestone=7.10.2)

**Comment by 630E6617** [comment]
Ghost: [Public Dev Meeting 15th June](http://dev.ghost.org/public-dev-meeting-15th-june/)
なかなか大変ですな。ほぼ一ヶ月の間、新バージョンがリリースされないというのは久しぶり。

**Comment by 630E6617** [comment]
[Milestone ghc 7.10.2](https://ghc.haskell.org/trac/ghc/milestone/7.10.2) 

As expected, it is delayed...

**Comment by 630E6617** [comment]
https://owncloud.org/changelog/desktop/?utm_campaign=releases

**Comment by 630E6617** [comment]
https://github.com/ghc/ghc/commit/9ea4ded2ee7822aed05275c390c285f0a60a6ef6
coming soon!

**Comment by 630E6617** [comment]
1.0リリースということでAtomに興味が出てきました。で、atomのパッケージを色々入れて設定をしていて**世の中には`latexmk`というものがある**ということを知りました。

うむむ、これは（時間は掛かるけど）latexによるpdf生成の究極兵器のようだ。

残念なことに世の中にはまだdvi経由でpdfを生成している人が多いみたいなので直接pdfを吐き出すutf8 対応な日本語lualatex用に[設定ファイル](https://gist.github.com/630E6617/e164db4c558e1fc79ee3) を作ってみました。

**Comment by 630E6617** [comment]
[magit 2.1.0](https://github.com/magit/magit) released.

**Comment by 630E6617** [comment]
magit 2.1.0 に上げてから、シンボリックリンクを使ってワーキングツリーの中のディレクトリをシンボリックリンクで指している状況でリポジトリを見つけきれないエラーが出るようになってかなり困った。これは相対リンクをやめて絶対パスでシンボリックリンクを張り直したら問題解決。よかった。

**Comment by 630E6617** [comment]
linux-4.1.1 in [testing] は1日に1回程度の頻度でクラッシュする。戻すしかなさそうだ。

**Comment by 630E6617** [comment]
kernel-4.1.2 in [testing] も入れてすぐクラッシュした。4.1.2なのに！？ こんなに安定しないのははじめてかも。

**Comment by 630E6617** [comment]
gitのリポジトリを立ててpullできるのにpush出来ないとき。
もし [git-http-http](http://git-scm.com/docs/git-http-backend) を使っているなら、`http.receivepack`を設定してないせいだろう。なかなかズバリ答えているページがないのでちょっと時間が掛かってしまった。
