### ISSUE TITLE
gnome環境下でのgpg

### ISSUE THREAD

**Issue by 630E6617** [630E6617/activity#6]
パスフレーズをキャッシュしてくれなくなったので非常に使いにくい。なんとかしたい。

**Comment by b0101** [comment]
### renewal gpg

[arch wiki](https://wiki.archlinux.org/index.php/GnuPG)に従って更新してみた

* `~/.gnupg/gpg.conf`に設定追加
* regenerate, どうせなら最強としよう、RSA 4096bitを選択：
```
gpg --full-gen-key
```
* 古い方のアドレスを変えて*uid*が被らないようにする。

    1. `adduid`で別アドレスを追加
    1. `uid`で古いアドレスを選択
    1. `deluid`で削除
* pgp.mit.eduに登録

**Comment by b0101** [comment]
持ってくるのを忘れた。

**Comment by b0101** [comment]
[マニュアル](http://syogimonopoly.homeip.net/GPH/manual.html) 見とくべき。

**Comment by b0101** [comment]
公開鍵は鍵サーバーに入れておけばクラウドに保管する必要ないね。秘密鍵はそもそもそういうところに置くべきものじゃないし。ということはgpgの個人情報はクラウドに置くべきものは何もないのだった。

**Comment by b0101** [comment]
edit-keyで`adduid`しようとするとエラーが出る。

**Comment by b0101** [comment]
`adduser`しようとしているうちに「ユーザIDが見つかりません」状態になってしまった。

**Comment by b0101** [comment]
* 自分の鍵を鍵サーバーからimportすると、なぜか秘密鍵があることになる
* `gpg -K`で見るとそこには`sec#`と出る。`#`とは何者。ぐぐっても全然わからない。

**Comment by b0101** [comment]
新しい鍵を作り、複数のuser idを設定して鍵問題解決。

**Comment by b0101** [comment]
ついでにノートPCには秘密鍵を配るのはやめよう。ネットにつながっているなら母機上で復号化すればいいのだから。
